spring:
  application:
    name: FranArtistSite

  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/franartist
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    type: org.postgresql.ds.PGSimpleDataSource
    generate-unique-name: true

  aws:
    s3:
      bucket: franwebsiteart
      region: us-east-2
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      endpoint-url: https://franwebsiteart.s3.amazonaws.com
